module.exports = [
  '<span>{{company.name}}</span>',
  '<span>{{company.number}}</span>',
  '<span>{{company.address}}</span>',
  
  '<div>Invoice details</div>',
  '<span>{{invoice.number}}</span>',
  '<span>{{invoice.date}}</span>',
  '<span>{{invoice.dueDate}}</span>',
  
  '<span>{{company.name}}</span>',
  '<span>{{company.number}}</span>',
  '<span>{{company.address}}</span>',
  
  '<h1>Services</h1>',
  '<table>',
    '<thead>',
      '<tr>',
        '<th>type</th>',
        '<th>rate</th>',
        '<th>worked</th>',
      '</tr>',
    '</thead>',
    '{{#services}}',
      '<tr>',
        '<td>{{type}}</td>',
        '<td>{{rate.value}} per {{rate.unit}}</td>',
        '<td>',
          '<table>',
            '<tr>',
              '<th>Date</th>',
              '<th>Project</th>',
              '<th>measurement</th>',
            '</tr>',
            '{{#worked}}',
              '<tr>',
                '<td>{{date}}</td>',
                '<td>{{project}}</td>',
                '<td>{{measurement}}</td>',
              '</tr>',
            '{{/worked}}',
          '</table>',
        '</td>',
        '<tr> Total due: {{billable}} </tr>',
      '</tr>',
    '{{/services}}',
  '</table>'
].join('\n');